// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWub5rul6SADr7uwA-MnAneuHUvQTJR00',
    appId: '1:440263003646:web:0fcc7e32bdeefc97bc44af',
    messagingSenderId: '440263003646',
    projectId: 'e-commerce-e2a75',
    authDomain: 'e-commerce-e2a75.firebaseapp.com',
    storageBucket: 'e-commerce-e2a75.appspot.com',
    measurementId: 'G-ME4JN9J44T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCT8chUJTLlyX6BZATGXkCiQLT_drrP1s',
    appId: '1:440263003646:android:dd9734ea7bb85134bc44af',
    messagingSenderId: '440263003646',
    projectId: 'e-commerce-e2a75',
    storageBucket: 'e-commerce-e2a75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4JttRglxTsC6kBmmrynwRTukJYem37xM',
    appId: '1:440263003646:ios:729262308f4bb062bc44af',
    messagingSenderId: '440263003646',
    projectId: 'e-commerce-e2a75',
    storageBucket: 'e-commerce-e2a75.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4JttRglxTsC6kBmmrynwRTukJYem37xM',
    appId: '1:440263003646:ios:729262308f4bb062bc44af',
    messagingSenderId: '440263003646',
    projectId: 'e-commerce-e2a75',
    storageBucket: 'e-commerce-e2a75.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWub5rul6SADr7uwA-MnAneuHUvQTJR00',
    appId: '1:440263003646:web:1b0d02ccbe9cee1abc44af',
    messagingSenderId: '440263003646',
    projectId: 'e-commerce-e2a75',
    authDomain: 'e-commerce-e2a75.firebaseapp.com',
    storageBucket: 'e-commerce-e2a75.appspot.com',
    measurementId: 'G-V5R7CPQWYQ',
  );
}
